version: '3.7'

services:
  # nginx - web server
  nginx:
    build:
      context: ./config/docker/nginx
    env_file:
      - ./.env
    init: true
    links:
      - php
    ports:
      - "8000:80"
    volumes:
      - cpresources:/var/www/project/web/cpresources
      - ./web:/var/www/project/web:cached
  # php - personal home page
  php:
    build:
      context: ./config/docker/php
    depends_on:
      - "mariadb"
      # - "redis"
    env_file:
      - ./.env
    expose:
      - "9000"
    init: true
    # links:
    #   - mariadb
      # - redis
    volumes:
      - cpresources:/var/www/project/web/cpresources
      - storage:/var/www/project/storage
      - .:/var/www/project:cached
      - ./vendor:/var/www/project/vendor:delegated
      - ./storage/logs:/var/www/project/storage/logs:delegated
  # queue - runs queue jobs via ./craft queue/listen
  # queue:
  #   build:
  #     context: ./config/docker/php
  #   command: ./craft queue/listen 10
  #   depends_on:
  #     - "php"
  #   env_file:
  #     - ./.env
  #   expose:
  #     - "9001"
  #   init: true
  #   links:
  #     - mariadb
  #     - redis
  #   volumes:
  #     - cpresources:/var/www/project/web/cpresources
  #     - storage:/var/www/project/storage
  #     - .:/var/www/project:cached
  #     - ./vendor:/var/www/project/vendor:delegated
  #     - ./storage/logs:/var/www/project/storage/logs:delegated
  # mariadb - database
  mariadb:
    build:
      context: ./config/docker/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    init: true
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
  # redis - key/value database for caching & php sessions
  # redis:
  #   build:
  #     context: ./config/docker/redis
  #   expose:
  #     - "6379"
  #   init: true
  # webpack - frontend build system
  # webpack:
  #   build:
  #     context: ./config/docker/webpack
  #   env_file:
  #     *env
  #   init: true
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./tsconfig.json:/var/www/project/tsconfig.json:cached
  #     - ./buildchain:/var/www/project/buildchain:cached
  #     - ./buildchain/node_modules:/var/www/project/buildchain/node_modules:delegated
  #     - ./cms/web/dist:/var/www/project/cms/web/dist:delegated
  #     - ./src:/var/www/project/src:cached
  #     - ./cms/templates:/var/www/project/cms/templates:cached

volumes:
  db-data:
  cpresources:
  storage: