version: '3.7'

x-service: &service
  init: true
  env_file: .env

services:
  nginx:
    <<: *service
    build: ./config/docker/nginx
    depends_on:
      - "php"
    ports:
      - "8000:80"
    volumes:
      - cpresources:/app/web/cpresources
      - ./web:/app/web:cached
    container_name: nginx
  php:
    <<: *service
    build: ./config/docker/php
    depends_on:
      - "mariadb"
      # - "redis"
    expose:
      - "9000"
    volumes:
      - cpresources:/app/web/cpresources
      - storage:/app/storage
      - .:/app:cached
      - ./vendor:/app/vendor:delegated
      - ./storage/logs:/app/storage/logs:delegated
    container_name: php
  cli:
    <<: *service
    build: ./config/docker/php
    command: ./craft queue/listen 10
    depends_on:
      - "php"
    expose:
      - "9001"
    volumes:
      - cpresources:/app/web/cpresources
      - storage:/app/storage
      - .:/app:cached
      - ./vendor:/app/vendor:delegated
      - ./storage/logs:/app/storage/logs:delegated
    container_name: cli
  mariadb:
    <<: *service
    build: ./config/docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: steadfast
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    container_name: mariadb
  redis:
    <<: *service
    build: ./config/docker/redis
    expose:
      - "6379"
    container_name: redis

volumes:
  db-data:
  cpresources:
  storage: